[package]
name = "tiny_ped_com"
version = "0.1.0"
license = "MIT"
authors = ["Alex Ledger <alex@alexledger.net"]
description = "A small Rust library for Pedersen commitments over elliptic curves."

[dependencies]
curve25519-dalek = "^0.16"
rand = { version = "0.4", optional = false }
